### ISSUE TITLE
"Building Smoothness Cost" runs slowly 

### ISSUE THREAD

**Issue by Owen1234560** [mickare/Deformation-Transfer-for-Triangle-Meshes#2]
When the number of mesh faces is large, "Building Smoothness Cost" runs very slowly and takes up a lot of memory. Is there any optimization method?
Thanks.

**Comment by mickare** [comment]
Hi Owen,
thanks for reporting it. Could you give the new commit ( 5809c92 ) a try?

**Comment by Owen1234560** [comment]
> Hi Owen,
> thanks for reporting it. Could you give the new commit ( [5809c92](https://github.com/mickare/Deformation-Transfer-for-Triangle-Meshes/commit/5809c92ddcaecc6df45443e3109a3848b55d9045) ) a try?

**Comment by Owen1234560** [comment]
Hi, mickare.
It works. Thank you very much.

**Comment by mickare** [comment]
:+1:
